// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteGlossaryEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExportProject(arg1:string,arg2:string):Promise<void>;

export function ExportProjectText(arg1:string,arg2:string):Promise<void>;

export function FetchBookDetails(arg1:string):Promise<main.BookDetailsInfo>;

export function FixTranslation(arg1:string,arg2:number):Promise<void>;

export function GetBookDetailsInfo(arg1:string):Promise<main.BookDetailsInfo>;

export function GetGlossary(arg1:string):Promise<Record<string, string>>;

export function GetLastPosition(arg1:string):Promise<main.Position>;

export function GetLog():Promise<Array<string>>;

export function GetParagraph(arg1:string,arg2:number,arg3:boolean):Promise<main.ParagraphInfo>;

export function GetParagraphsBatch(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<main.ParagraphInfo>>;

export function GetProjectCover(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function ImportEPUB(arg1:string,arg2:string,arg3:string):Promise<main.ProjectInfo>;

export function ImportProjectFile(arg1:string):Promise<main.ProjectInfo>;

export function ListProjects():Promise<Array<main.ProjectInfo>>;

export function LoadProject(arg1:string):Promise<main.ProjectInfo>;

export function OpenEPUBDialog():Promise<string>;

export function OpenProjectDialog():Promise<string>;

export function SaveBookDetailsInfo(arg1:string,arg2:main.BookDetailsInfo):Promise<void>;

export function SavePosition(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SaveProject(arg1:string):Promise<void>;

export function SaveProjectDialog(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveTextDialog(arg1:string):Promise<string>;

export function SetGlossaryEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetTranslation(arg1:string,arg2:number,arg3:string):Promise<void>;

export function TranslateParagraph(arg1:string,arg2:number):Promise<void>;

export function TranslateParagraphs(arg1:string,arg2:number):Promise<void>;
