// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGlossaryEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteGlossaryEntry'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportProject(arg1, arg2) {
  return window['go']['main']['App']['ExportProject'](arg1, arg2);
}

export function ExportProjectText(arg1, arg2) {
  return window['go']['main']['App']['ExportProjectText'](arg1, arg2);
}

export function FetchBookDetails(arg1) {
  return window['go']['main']['App']['FetchBookDetails'](arg1);
}

export function FixTranslation(arg1, arg2) {
  return window['go']['main']['App']['FixTranslation'](arg1, arg2);
}

export function GetBookDetailsInfo(arg1) {
  return window['go']['main']['App']['GetBookDetailsInfo'](arg1);
}

export function GetGlossary(arg1) {
  return window['go']['main']['App']['GetGlossary'](arg1);
}

export function GetLastPosition(arg1) {
  return window['go']['main']['App']['GetLastPosition'](arg1);
}

export function GetLog() {
  return window['go']['main']['App']['GetLog']();
}

export function GetParagraph(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetParagraph'](arg1, arg2, arg3);
}

export function GetParagraphsBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetParagraphsBatch'](arg1, arg2, arg3, arg4);
}

export function GetProjectCover(arg1) {
  return window['go']['main']['App']['GetProjectCover'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportEPUB(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportEPUB'](arg1, arg2, arg3);
}

export function ImportProjectFile(arg1) {
  return window['go']['main']['App']['ImportProjectFile'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenEPUBDialog() {
  return window['go']['main']['App']['OpenEPUBDialog']();
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function SaveBookDetailsInfo(arg1, arg2) {
  return window['go']['main']['App']['SaveBookDetailsInfo'](arg1, arg2);
}

export function SavePosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePosition'](arg1, arg2, arg3);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectDialog(arg1) {
  return window['go']['main']['App']['SaveProjectDialog'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTextDialog(arg1) {
  return window['go']['main']['App']['SaveTextDialog'](arg1);
}

export function SetGlossaryEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGlossaryEntry'](arg1, arg2, arg3);
}

export function SetTranslation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTranslation'](arg1, arg2, arg3);
}

export function TranslateParagraph(arg1, arg2) {
  return window['go']['main']['App']['TranslateParagraph'](arg1, arg2);
}

export function TranslateParagraphs(arg1, arg2) {
  return window['go']['main']['App']['TranslateParagraphs'](arg1, arg2);
}
